import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './auth/nav'

const inter = Inter({ 
  subsets: ['latin'], 
weight:["400","700"],
variable:"--font-inter" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96 ${inter.variable} bg-gray-200`}>
        <Nav/>
        {children}
        </body>
    </html>
  )
}
